In [2]:
import pandas as pd
import numpy as np

%matplotlib inline

In [3]:
data_raw = pd.read_csv("data/Hotel Reservations.csv")

In [5]:
data_raw.drop(columns=['Booking_ID', 'arrival_year', 'arrival_month', 'arrival_date'])

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,65.00,0,Not_Canceled
1,2,0,2,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,Not_Canceled
2,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,60.00,0,Canceled
3,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,0,Canceled
4,2,0,1,1,Not Selected,0,Room_Type 1,48,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,Online,0,0,0,167.80,1,Not_Canceled
36271,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,Online,0,0,0,90.95,2,Canceled
36272,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,Online,0,0,0,98.39,2,Not_Canceled
36273,2,0,0,3,Not Selected,0,Room_Type 1,63,Online,0,0,0,94.50,0,Canceled
36274,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,Offline,0,0,0,161.67,0,Not_Canceled

# Data Cleaning
* % canceled reservations = no_of_previous_cancellations/(no_of_previous_cancellations+no_of_previous_bookings_not_canceled)
* make no_children => children (0 or 1 bianry)
* new column "total number of nights" = no_of_weekend_nights + no_of_week_nights

In [ ]:
# Preprocessing

numerical_columns = ["no_of_adults", "total number of nights", "lead_time", "% canceled reservations", "average_price_per_room", "no_of_special_requests" ]
categorical_columns = ["type_of_meal_plan", "room_type_reserved", "market_segment_type"]
binary_columns = ["children", "repeated_guest", "required_car_parking_space" ]